{{$a:=`🎉`}}{{$d:=0}}{{$k:=""}}{{$f:=""}}{{$C:=""}}{{$i:=0}}{{if not .ExecData}}{{$k =.CmdArgs}}{{$f =reReplace `\A\s+|\s+\z` .StrippedMsg ""}}{{$C =.Cmd}}{{else if toInt .ExecData}}{{$i =str .ExecData}}{{else if eq (printf "%T" .ExecData) "string"}}{{$t:=split .ExecData " "}}{{if gt (len $t) 1}}{{$f =reReplace `(\A\s+)|(\s+\z)` (joinStr " " (slice $t 1)) ""}}{{$C =index $t 0}}{{$k =split (reReplace `\s{2,}` $f " ") " "}}{{end}}{{end}}{{if  not $i}}{{if gt (len $k) 0}}{{$l:=lower (index $k 0)}}{{if or (gt (len $k) 1) (eq $l "list") (eq $l "reroll")}}{{if eq $l "start"}}{{$k:=reReplace (print `(?i)\A` $l `\s*`) $f ""}}{{$u:=-1}}{{$w:=1}}{{$x:=.Channel.ID}}{{$G:=""}}{{$D:=toInt (currentTime.Sub (newDate 2019 10 10 0 0 0)).Seconds}}{{with reFindAllSubmatches `(?i)-w (\d+)(?:\s+|\z)` $k}}{{$k =reReplace (index . 0 0) $k ""}}{{$w =toInt (index . 0 1)}}{{end}}{{with reFindAllSubmatches `(?i)-p (\d+)(?:\s+|\z)` $k}}{{$k =reReplace (index . 0 0) $k ""}}{{$u =toInt (index . 0 1)}}{{end}}{{with reFindAllSubmatches `(?i)(-c (?:<#)?(\d+)>?(?:\s+|$))` $k}}{{$k =reReplace (index . 0 0) $k ""}}{{$x =index . 0 2}}{{end}}{{$y:=split $k  " "}}{{$j:=toDuration (index $y 0)}}{{$p:=""}}{{if gt (len $y) 1}}{{$p =joinStr " " (slice $y 1)}}{{end}}{{$p =reReplace `\A\s+` $p ""}}{{if and ($j)  ($p)}}{{if or (ge $u $w) (eq $u -1)}}{{with (sendMessageNoEscapeRetID $x cembed)}}{{$G =joinStr "" $x .}}{{$b:=sdict "chan" $x "count" 0 "ID" $G "listID" "" "maxWinners"  $w "maxParticipants" $u "expiresAt" (currentTime.Add $j) "prize" $p "uID" $D "host" $.User.Mention}}{{addMessageReactions $x . $a}}{{$z:=print  `>>> **Prize : **` $p "\n\n"}}{{if gt $w 0}}{{$z =print $z "**Max Winners :** " $w}}{{end}}{{if gt $u 0}}{{$z =print $z "⠀⠀⠀⠀⠀**Max Participants :** " $u}}{{end}}{{$z =print $z "\n\n**Hosted By :** " $.User.Mention "\n\n**React with " $a " to enter GiveAway **"}}{{editMessageNoEscape $x . (cembed "title" "🌟🌟**GiveAway Started !!**🌟🌟" "description"  $z "color" 16763170 "footer" (sdict "text" (print "ID: " $D " | GiveAway Ends " )) "timestamp" $b.expiresAt)}}{{$m:=sdict (or (dbGet 7777 "giveaway_active").Value sdict)}}{{$m.Set $G $b}}{{dbSet 7777 "giveaway_active" $m}}{{$m =sdict (or (dbGet 7777 "giveaway_active_IDs").Value sdict)}}{{$m.Set (str $D) $G}}{{dbSet 7777 "giveaway_active_IDs" $m}}{{scheduleUniqueCC $.CCID $x $j.Seconds $D  $G}}{{else}}
**Invalid Channel !!**
{{end}}{{else}}
**Error:** Max Winners cannot be more than Max Participants!!
{{end}}{{else}}
**Error:** Invalid Duration or Prize !!
{{end}}{{else if eq $l "end"}}{{$D:=index $k 1}}{{with (dbGet 7777 "giveaway_active").Value}}{{$G:=index (dbGet 7777 "giveaway_active_IDs").Value $D}}{{with (index . (str $G))}}{{cancelScheduledUniqueCC $.CCID .uID}}{{$H:=sendTemplate .chan "g_end" "ID" (str $G)}}{{else}}
**Error:** Invalid ID ``{{$D}}``
{{end}}{{else}}
**Error:** No Active Giveaways.
{{end}}{{else if eq $l "cancel"}}{{$D:=index $k 1}}{{$G:=0}}{{with (dbGet 7777 "giveaway_active").Value}}{{$A:=(dbGet 7777 "giveaway_active_IDs").Value}}{{$G =index $A $D}}{{with (index . (str $G))}}{{$x:=.chan}}{{$p:=.prize}}{{$B:=.host}}{{cancelScheduledUniqueCC $.CCID .uID}}{{$E:=index ( split $G (str $x)) 1}}{{with (getMessage $x $E )}}{{editMessage $x $E (cembed "title" "🌟🌟**GiveAway Cancelled !!**🌟🌟" "description" (print ">>> **Prize :** "  $p "\n\n**Hosted By : **" $B) "footer" (sdict "text" "Giveaway Cancelled") "color" 12257822 )}}{{end}}Done!

{{else}}
**Error:** Invalid ID ``{{$D}}``
{{end}}{{if $G}}{{$h:=sdict .}}{{$h.Del $G}}{{dbSet 7777 "giveaway_active" $h}}{{$h =sdict $A}}{{$h.Del $D}}{{dbSet 7777 "giveaway_active_IDs" $h}}{{end}}{{else}}
**Error:** No Active Giveaways.
{{end}}{{else if eq $l "reroll"}}{{$G:=1}}{{if gt (len $k) 1}}{{$G =toInt (index $k 1)}}{{end}}{{$q:=false}}{{if ($I:=(dbGet 7777 "giveaway_old").Value)}}{{range $i,$J:=$I}}{{if or (eq (sub (len $I) $i) $G) (eq (toInt $J.uID) $G)}}{{$q =true}}{{$H:=sendTemplate $J.chan "g_end" "ID" (str $J.ID) "Data" $J}}{{end}}{{end}}{{if not $q}}**Error** - Invalid Argument `{{index $k 1}}`. Old Giveaway with corresponding ID or Position(1-10) not found!{{end}}{{else}}
**Error:** No Old Giveaways.
{{end}}{{else if eq $l "list"}}{{with (dbGet 7777 "giveaway_active").Value}}{{$r:=0}}{{range $k , $J:=.}}{{$r =add $r 1}}{{$r}}) **ID:** ``{{$J.uID}}``  **Prize:** ``{{$J.prize}}``
**Ends AT:** ``{{formatTime $J.expiresAt}}``
{{end}}{{else}}
No Active Giveaways.
{{end}}{{else}}{{$d =1}}{{end}}{{else}}{{$d =1}}{{end}}{{else}}{{$d =1}}{{end}}{{else}}{{$H:=sendTemplate nil "g_end" "ID" $i}}{{end}}{{define "g_end"}}{{$G:=.TemplateArgs.ID}}{{$x:=.Channel.ID}}{{$m:=(dbGet 7777 "giveaway_active").Value}}{{with .TemplateArgs.Data}}{{$m =sdict (str $G) .}}{{end}}{{if $m}}{{with (index $m $G)}}{{$c:=toInt .maxWinners}}{{$r:=toInt .count}}{{if lt $r $c}}{{$c =$r}}{{end}}{{$E:=index ( split $G (str $x)) 1}}{{$n:=.listID}}{{if and (gt $r .maxParticipants) (gt .maxParticipants 0)}}{{$r =.maxParticipants}}{{$n =joinStr "," (slice (split $n ",") 0 $r) ""}}{{end}}{{$g:=""}}{{range seq 0 $c}}{{$o:=index (split $n ",") (randInt 0 $r )}}{{$n =reReplace (print $o ",") $n ""}}{{$r =add $r -1}}{{$g =(print $g "<@" $o "> ")}}{{end}}{{$z:=print ">>> **Prize :** " .prize "\n\n**Winners :** "}}{{if  $c}}{{$z =print $z $g}}{{else}}{{$z =print $z "No Participants :( "}}{{end}}{{$z:=print $z "\n\n**Hosted By :** " .host}}{{with (getMessage $x $E )}}{{editMessage $x $E (cembed "title" "🌟🌟**GiveAway Ended !!**🌟🌟" "description" $z "footer" (sdict "text" "Giveaway Ended at ") "timestamp" currentTime "color" 12257822 )}}{{end}}{{if $c}}{{sendMessage nil (print "**Prize :** " .prize "\n**Winner(s) :** " $g)}}{{else}}
**Giveaway Ended, No participants :( !!**
**Prize : {{.prize}}**
{{end}}{{if not $.TemplateArgs.Data}}{{$h:=sdict $m}}{{$h.Del $G}}{{dbSet 7777 "giveaway_active" $h}}{{$h =sdict (dbGet 7777 "giveaway_active_IDs").Value}}{{$h.Del (str .uID)}}{{dbSet 7777 "giveaway_active_IDs" $h}}{{$F:=cslice.AppendSlice (or (dbGet 7777 "giveaway_old").Value cslice)}}{{if gt (len $F) 9}}{{$F =slice $F 1}}{{end}}{{dbSet 7777 "giveaway_old" ($F.Append .)}}{{end}}{{else}}`Warning:` Invoked CC : {{$.CCID}} using ExecCC with invalid Giveaway ID.
{{end}}{{else}}`Warning:` Invoked CC : {{$.CCID}} using ExecCC with no active Giveaways.
{{end}}{{end}}{{if $d}}{{sendMessage nil (print "__**Incorrect Syntax** __ \n**Commands are :** \n```elm\n" ($C) " start <time : Duration> <prize : String> \n\noptional_flags \n-p (max participants : Number) \n-w (max winners : Number)\n-c (channel : Mention/ID)\n```\n```elm\n" ($C) " end <id : Number>```\n```elm\n" ($C) " cancel <id : Number>```\n```elm\n" ($C) " reroll [id or n giveaways old : Number]```\n```elm\n"  ($C) " list ``` ")}}{{end}}
