{{$a:=`🎉`}}{{$q:=.CCID}}{{$d:=0}}{{$k:=""}}{{$e:=""}}{{$z:=""}}{{$h:=0}}{{if not .ExecData}}{{$k =.CmdArgs}}{{$e =reReplace `\A\s+|(\s+\z)` .StrippedMsg ""}}{{$z =.Cmd}}{{else if toInt .ExecData}}{{$h =toString .ExecData}}{{else if eq (printf "%T" .ExecData) "string"}}{{$r:=split .ExecData " "}}{{if gt (len $r) 1}}{{$e =reReplace `(\A\s+)|(\s+\z)` (joinStr " " (slice (split .ExecData " ") 1)) ""}}{{$z =index $r 0}}{{$k =split (reReplace `\s{2,}` $e " ") " "}}{{end}}{{end}}{{if  not $h}}{{if gt ( len $k ) 0}}{{if or (gt (len $k) 1) (eq (lower (index $k 0) ) "list")}}{{if eq (lower (index $k 0) ) "start"}}{{$k:=joinStr " " (slice (split $e " ") 1 )}}{{$k =reReplace `\A\s+` $k ""}}{{$s:=-1}}{{$t:=1}}{{$u:=.Channel.ID}}{{$D:=""}}{{$l:=sdict}}{{$i:=toInt (currentTime.Sub (newDate 2019 10 10 0 0 0)).Seconds}}{{with reFindAllSubmatches `(?i)((-w) (\d+)(?:\s|$))` $k}}{{$k =reReplace `(?i)(-w \d+\s+)|(-w \d+$)` $k ""}}{{$t =toInt (index (index . 0) 3)}}{{end}}{{with reFindAllSubmatches `(?i)((-p) (\d+)(?:\s|$))` $k}}{{$k =reReplace `(?i)(-p \d+(\s+))|(-p \d+$)` $k ""}}{{$s =toInt (index (index . 0) 3)}}{{end}}{{with reFindAllSubmatches `(?i)(-c (?:<#)?(\d+)(?:>?)(?:\s|$))` $k}}{{$k =reReplace `(?i)(-c ((<#)?\d+(>?))\s+)|(-c ((<#)?\d+(>?))$)` $k ""}}{{$u =index (index . 0) 2}}{{end}}{{$w:=split $k  " "}}{{$A:=lower (index  $w 0)}}{{$o:=""}}{{if gt (len $w) 1}}{{$o =joinStr " " (slice $w 1)}}{{end}}{{$o =reReplace `\A\s+` $o ""}}{{$j:=toDuration $A}}{{if and ($j)  ($o)}}{{if or (ge $s $t) (eq $s -1)}}{{with (sendMessageNoEscapeRetID $u cembed)}}{{$D =(joinStr "" $u .)}}{{$b:=sdict "chan" $u "count" 0 "listID" "" "maxWinners"  $t "maxParticipants" $s "expiresAt" (currentTime.Add $j) "prize" $o "uID" $i}}{{addMessageReactions $u . $a}}{{$x:=(joinStr ``  `>>> **Prize : **` $o "\n\n")}}{{if gt $t 0}}{{$x =joinStr "" $x "**Max Winners :** " $t}}{{end}}{{if gt $s 0}}{{$x =joinStr "" $x "⠀⠀⠀⠀⠀**Max Participants :** " $s}}{{end}}{{$x =joinStr "" $x "\n\n**React with " $a " to enter GiveAway **"}}{{editMessageNoEscape $u . (cembed "title" "🌟🌟**GiveAway Started !!**🌟🌟" "description"  $x "color" 16763170 "footer" (sdict "text" (joinStr "" "ID: " $i " | GiveAway Ends " )) "timestamp" $b.expiresAt)}}{{with (dbGet 7777 "giveaway_active").Value}}{{$l =sdict .}}{{end}}{{$l.Set $D $b}}{{dbSet 7777 "giveaway_active" $l}}{{$l =sdict}}{{with (dbGet 7777 "giveaway_active_IDs").Value}}{{$l =sdict .}}{{end}}{{$l.Set (toString $i) $D}}{{dbSet 7777 "giveaway_active_IDs" $l}}{{scheduleUniqueCC (toInt $q) $u $j.Seconds $i  $D}}{{else}}
**Invalid Channel !!**
{{end}}{{else}}
**Error:** Max Winners cannot be more than Max Participants!!
{{end}}{{else}}
**Error:** Invalid Duration or Prize !!
{{end}}{{else if eq (lower (index $k 0) ) "end"}}{{$B:=index $k 1}}{{with (dbGet 7777 "giveaway_active").Value}}{{$D:=index (dbGet 7777 "giveaway_active_IDs").Value $B}}{{with (index . (toString $D))}}{{scheduleUniqueCC (toInt $q) .chan 1  .uID $D}}{{else}}
**Error:** Invalid ID ``{{$B}}``
{{end}}{{else}}
**Error:** No Active Giveaways.
{{end}}{{else if eq (lower (index $k 0) ) "cancel"}}{{$B:=index $k 1}}{{$D:=0}}{{with (dbGet 7777 "giveaway_active").Value}}{{$y:=(dbGet 7777 "giveaway_active_IDs").Value}}{{$D =index $y  $B}}{{with (index . (toString $D))}}{{$u:=.chan}}{{$o:=.prize}}{{cancelScheduledUniqueCC (toInt $q) .uID}}{{$C:=index ( split $D (toString $u)) 1}}{{with (getMessage $u $C )}}{{editMessageNoEscape $u $C (cembed "title" "🌟🌟**GiveAway Cancelled !!**🌟🌟" "description" (joinStr "" ">>> **Prize:** "  $o) "footer" (sdict "text" "Giveaway Cancelled") "color" 12257822 )}}{{end}}Done!

{{else}}
**Error:** Invalid ID ``{{$B}}``
{{end}}{{if $D}}{{$g:=sdict .}}{{$g.Del $D}}{{dbSet 7777 "giveaway_active" $g}}{{$g =sdict $y}}{{$g.Del $B}}{{dbSet 7777 "giveaway_active_IDs" $g}}{{end}}{{else}}
**Error:** No Active Giveaways.
{{end}}{{else if eq (lower (index $k 0) ) "list"}}{{with (dbGet 7777 "giveaway_active").Value}}{{$p:=0}}{{range $k , $E:=.}}{{$p =add $p 1}}{{$p}}) **ID:** ``{{$E.uID}}``  **Prize:** ``{{$E.prize}}``
**Ends AT:** ``{{formatTime $E.expiresAt}}``
{{end}}{{else}}
No Active Giveaways.
{{end}}{{else}}{{$d =1}}{{end}}{{else}}{{$d =1}}{{end}}{{else}}{{$d =1}}{{end}}{{else}}{{$D:=$h}}{{$u:=.Channel.ID}}{{$l:=(dbGet 7777 "giveaway_active" ).Value}}{{if $l}}{{with (index $l $D)}}{{$c:=toInt .maxWinners}}{{$p:=toInt .count}}{{if lt $p $c}}{{$c =$p}}{{end}}{{$C:=index ( split $D (toString $u)) 1}}{{$m:=.listID}}{{if and (gt $p .maxParticipants) (gt .maxParticipants 0)}}{{$p =.maxParticipants}}{{$m =joinStr "," (slice (split $m ",") 0 $p) ""}}{{end}}{{$f:=""}}{{range seq 0 $c}}{{$n:=index (split $m ",") (randInt 0 $p )}}{{$m =reReplace (joinStr "" $n ",") $m ""}}{{$p =add $p -1}}{{$f =(joinStr "" $f "<@" $n "> ")}}{{end}}{{$x:=joinStr "" ">>> **Prize:** " .prize "\n\n**Winners:** "}}{{if  $c}}{{$x =joinStr "" $x $f}}{{else}}{{$x =joinStr "" $x "No Participants :( "}}{{end}}{{with (getMessage $u $C )}}{{editMessageNoEscape $u $C (cembed "title" "🌟🌟**GiveAway Ended !!**🌟🌟" "description" $x "footer" (sdict "text" "Giveaway Ended at ") "timestamp" currentTime "color" 12257822 )}}{{end}}{{if $c}}{{sendMessage nil (joinStr "" "**Prize:** " .prize "\n**Winner(s) :** " $f)}}{{else}}
**Giveaway Ended, No participants :( !!**
**Prize : {{.prize}}**
{{end}}{{$g:=sdict $l}}{{$g.Del $D}}{{dbSet 7777 "giveaway_active" $g}}{{$g =sdict (dbGet 7777 "giveaway_active_IDs").Value}}{{$g.Del (toString .uID)}}{{dbSet 7777 "giveaway_active_IDs" $g}}{{else}}`Warning:` Invoked CC : {{$q}} using ExecCC with invalid Giveaway ID.
{{end}}{{else}}`Warning:` Invoked CC : {{$q}} using ExecCC with no active Giveaways.
{{end}}{{end}}{{if $d}}{{sendMessage nil (joinStr "" "__**Incorrect Syntax** __ \n**Commands are :** \n```elm\n" ($z) " start <Time> [Prize] \n\noptional_flags \n-p (max participants : Number) \n-w (max winners : Number)\n-c (channel : Mention/ID)\n```\n```elm\n" ($z) " end <ID>```\n```elm\n" ($z) " cancel <ID>```\n```elm\n" ($z) " list ``` ")}}{{end}}
